import { Config } from './config';
import { IKalenderEvent, iCalEvent } from './event';

/** Declaration file generated by dts-gen */

export class KalenderEvents {
    constructor(config: Config);
    convertEvent(e: iCalEvent): IKalenderEvent;
    convertEvents(events: any): any;
    convertScrapegoat(e: any): any;
    formatDate(_date: any, _end: any, withTime: any, fullday: any): any;
    getEvents(config?: Config): Promise<IKalenderEvent[]>;
}

