import { Config } from './config';

/** Declaration file generated by dts-gen */

export class KalenderEvents {
    constructor(config: Config);
    convertEvent(e: any): any;
    convertEvents(events: any): any;
    convertScrapegoat(e: any): any;
    formatDate(_date: any, _end: any, withTime: any, fullday: any): any;
    getEvents(config: any): any;
}

